#!/bin/bash
# 此脚本用于使修改 core.wxvpkg 内的代码及时生效
set -e
root_dir=$(cd `dirname $0`/.. && pwd -P)
a=$1
if [ "$a" == '1' ];then
  # 解压
  rm -rf "$root_dir/package.nw/core.wxvpkg.ext"
  node tools/wxvpkg_unpack.js "$root_dir/package.nw/core.wxvpkg" "$root_dir/package.nw/core.wxvpkg.ext"
  mv "$root_dir/package.nw/core.wxvpkg" "$root_dir/package.nw/core.wxvpkg.orgi"
else
  # 打包测试
  node tools/wxvpkg_pack.js package.nw/core.wxvpkg.ext package.nw/core.wxvpkg
  rm -rf ~/.config/wechat-devtools/WeappCache
  rm -rf ~/.config/wechat-devtools/WeappVendor
  unset https_proxy
  unset http_proxy
  unset all_proxy
  bin/wechat-devtools
fi