#!/bin/bash

root_dir=$(cd `dirname $0`/.. && pwd -P)
export PATH="$root_dir/node/bin:$PATH"

module="spdlog"
cd "$root_dir/tmp"
mkdir -p node_test/node_modules
cd node_test
npm install $module --save
rm -rf "$root_dir/package.nw/node_modules/$module"
cp -rf "$root_dir/tmp/node_test/node_modules/$module" "$root_dir/package.nw/node_modules"
