#!/bin/bash

root_dir=$(cd `dirname $0`/.. && pwd -P)

qemu-system-loongarch64 \
    -m 8G \
    -cpu la464-loongarch-cpu \
    -machine virt \
    -smp 8 \
    -bios QEMU_EFI.fd \
    -serial stdio \
    -device virtio-gpu-gl-pci \
    -display sdl,gl=on \
    -accel tcg,thread=multi \
    -net nic -net user \
    -device nec-usb-xhci,id=xhci,addr=0x1b \
    -device usb-tablet,id=tablet,bus=xhci.0,port=1 \
    -device usb-kbd,id=keyboard,bus=xhci.0,port=2 \
    -nic user,model=virtio-net-pci,hostfwd=tcp::5555-:22 \
    -virtfs local,path=.,mount_tag=host0,security_model=passthrough,id=host0 \
    -hda debian.qcow2