#!/usr/bin/env node

console.log("12312")
// console.log(process.platform); // linux
// const cmdPaths = [];
// cmdPaths.push("/System/Applications/Utilities/Terminal.app",
//     "/Applications/Utilities/Terminal.app"
// )

// console.log(cmdPaths);
console.log(process.env.comspec)
