#!/bin/bash

root_dir=$(cd `dirname $0`/../.. && pwd -P)
pkg_dir="/mnt/disk1/Project/WeCuit-Project/WeCuit-Mini-uni-test_uni_vue-cli/dist/build/mp-weixin"

cd "$pkg_dir" && \
wine $root_dir/package.nw/js/vendor/wcsc.exe "-db" "-pc" "54" "./pages/login/login.wxss" "./pages/index/index.wxss" "./pages/articleView/articleView.wxss" "./pages/calendar/calendar.wxss" "./pages/card/card.wxss" "./pages/checkIn/edit.wxss" "./pages/checkIn/list.wxss" "./pages/courseTable/courseTable.wxss" "./pages/courseTable/imgCropper/imgCropper.wxss" "./pages/exam/exam.wxss" "./pages/grade/grade.wxss" "./pages/laboratory/list.wxss" "./pages/laboratory/detail.wxss" "./pages/maintenance/maintenance.wxss" "./pages/my/ADMag/ADMag.wxss" "./pages/my/ADMag/watchAD/watchAD.wxss" "./pages/my/dataMag/dataMag.wxss" "./pages/my/my.wxss" "./pages/my/sub/sub.wxss" "./pages/my/sso/sso.wxss" "./pages/newsList/newsList.wxss" "./pages/officeGrade/query.wxss" "./pages/THEOL/dir/dir.wxss" "./pages/THEOL/THEOL.wxss" "./pages/THEOL/tree/tree.wxss" "./pages/auth/auth.wxss" "./pages/my/bind/bind.wxss" "./pages/my/register/register.wxss" "./pages/my/bind/mini.wxss" "./pages/terms/privacy.wxss" "./pages/resources/list.wxss" "./pages/my/about.wxss" "./components/beat-char/beat-char.wxss" "./components/card.wxss" "./components/mytree/mytree.wxss" "./components/scroll/index.wxss" "./components/tab/index.wxss" "./miniprogram_npm/weui-miniprogram/cell/cell.wxss" "./miniprogram_npm/weui-miniprogram/cells/cells.wxss" "./miniprogram_npm/weui-miniprogram/loading/loading.wxss" "./node-modules/mp-html/dist/uni-app/components/mp-html/mp-html.wxss" "./node-modules/mp-html/dist/uni-app/components/mp-html/node/node.wxss" "./pages/my/info.wxss" "./uni_modules/uni-card/components/uni-card/uni-card.wxss" "./uni_modules/uni-icons/components/uni-icons/uni-icons.wxss" "./uni_modules/uni-row/components/uni-col/uni-col.wxss" "./uni_modules/uni-row/components/uni-row/uni-row.wxss" "./uni_modules/uni-title/components/uni-title/uni-title.wxss" "./wxcomponents/dynamicForm/components/timePicker/timePicker.wxss" "./wxcomponents/dynamicForm/index.wxss" "./wxcomponents/dynamicForm/vant/icon/index.wxss" "./wxcomponents/dynamicForm/vant/info/index.wxss" "./wxcomponents/dynamicForm/vant/uploader/index.wxss" "./wxcomponents/image-cropper/image-cropper.wxss" "./app.wxss" "./common/main.wxss" "./wxcomponents/dynamicForm/components/timePicker/timePicker-wxa-auto-dark.wxss" "./wxcomponents/dynamicForm/index-wxa-auto-dark.wxss" "./wxcomponents/dynamicForm/vant/common/index-wxa-auto-dark.wxss" "./wxcomponents/dynamicForm/vant/common/index.wxss" "./wxcomponents/dynamicForm/vant/icon/index-wxa-auto-dark.wxss" "./wxcomponents/dynamicForm/vant/info/index-wxa-auto-dark.wxss" "./wxcomponents/dynamicForm/vant/uploader/index-wxa-auto-dark.wxss" "-ll" > $root_dir/test/wcsc/compare/wine.json

echo "==================="

cd "$pkg_dir" && \
$root_dir/compiler/nodejs/wcsc "-db" "-pc" "54" "./pages/login/login.wxss" "./pages/index/index.wxss" "./pages/articleView/articleView.wxss" "./pages/calendar/calendar.wxss" "./pages/card/card.wxss" "./pages/checkIn/edit.wxss" "./pages/checkIn/list.wxss" "./pages/courseTable/courseTable.wxss" "./pages/courseTable/imgCropper/imgCropper.wxss" "./pages/exam/exam.wxss" "./pages/grade/grade.wxss" "./pages/laboratory/list.wxss" "./pages/laboratory/detail.wxss" "./pages/maintenance/maintenance.wxss" "./pages/my/ADMag/ADMag.wxss" "./pages/my/ADMag/watchAD/watchAD.wxss" "./pages/my/dataMag/dataMag.wxss" "./pages/my/my.wxss" "./pages/my/sub/sub.wxss" "./pages/my/sso/sso.wxss" "./pages/newsList/newsList.wxss" "./pages/officeGrade/query.wxss" "./pages/THEOL/dir/dir.wxss" "./pages/THEOL/THEOL.wxss" "./pages/THEOL/tree/tree.wxss" "./pages/auth/auth.wxss" "./pages/my/bind/bind.wxss" "./pages/my/register/register.wxss" "./pages/my/bind/mini.wxss" "./pages/terms/privacy.wxss" "./pages/resources/list.wxss" "./pages/my/about.wxss" "./components/beat-char/beat-char.wxss" "./components/card.wxss" "./components/mytree/mytree.wxss" "./components/scroll/index.wxss" "./components/tab/index.wxss" "./miniprogram_npm/weui-miniprogram/cell/cell.wxss" "./miniprogram_npm/weui-miniprogram/cells/cells.wxss" "./miniprogram_npm/weui-miniprogram/loading/loading.wxss" "./node-modules/mp-html/dist/uni-app/components/mp-html/mp-html.wxss" "./node-modules/mp-html/dist/uni-app/components/mp-html/node/node.wxss" "./pages/my/info.wxss" "./uni_modules/uni-card/components/uni-card/uni-card.wxss" "./uni_modules/uni-icons/components/uni-icons/uni-icons.wxss" "./uni_modules/uni-row/components/uni-col/uni-col.wxss" "./uni_modules/uni-row/components/uni-row/uni-row.wxss" "./uni_modules/uni-title/components/uni-title/uni-title.wxss" "./wxcomponents/dynamicForm/components/timePicker/timePicker.wxss" "./wxcomponents/dynamicForm/index.wxss" "./wxcomponents/dynamicForm/vant/icon/index.wxss" "./wxcomponents/dynamicForm/vant/info/index.wxss" "./wxcomponents/dynamicForm/vant/uploader/index.wxss" "./wxcomponents/image-cropper/image-cropper.wxss" "./app.wxss" "./common/main.wxss" "./wxcomponents/dynamicForm/components/timePicker/timePicker-wxa-auto-dark.wxss" "./wxcomponents/dynamicForm/index-wxa-auto-dark.wxss" "./wxcomponents/dynamicForm/vant/common/index-wxa-auto-dark.wxss" "./wxcomponents/dynamicForm/vant/common/index.wxss" "./wxcomponents/dynamicForm/vant/icon/index-wxa-auto-dark.wxss" "./wxcomponents/dynamicForm/vant/info/index-wxa-auto-dark.wxss" "./wxcomponents/dynamicForm/vant/uploader/index-wxa-auto-dark.wxss" "-ll" > $root_dir/test/wcsc/compare/nodejs.json