#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

if (fs.existsSync(path.resolve(__dirname, "../nwjs"))) {
    if (!fs.existsSync(path.resolve(__dirname, "../nwjs/package.nw"))) {
        // 链接
        fs.symlinkSync(
            path.resolve(__dirname, "../package.nw"),
            path.resolve(__dirname, "../nwjs/package.nw")
        );
    }
}
