name: Build tar.gz AppImage

on:
  workflow_call:

jobs:
  build-tar:
    name: Build tar.gz AppImage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ARCH: ['x86_64']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Inspect directory after downloading artifacts
        run: |
          ls -alFR wechat-devtools-*.build
          ls -alFR wechat-devtools-*.src
      - name: Prepare
        run: echo "$(id -u), $(id -g)"

      - name: Generate TAG
        id: tag
        env:
          IS_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          tag='continuous'
          name='Continuous Build'
          if [[ "$IS_TAG" == 'true' ]]; then
            tag="$REF_NAME"
            name="$REF_NAME"
          fi
          echo "tag result: $tag - $name"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "name=$name" >> "$GITHUB_OUTPUT"

      - name: Build
        env:
          ACTION_MODE: 'true'
          WINE: 'false'
        run: |
          mkdir -p tmp/build
          tools/build-prepare.sh
          tools/build-release.sh ${{ matrix.ARCH }} ${{ steps.tag.outputs.tag }}

      - name: View Directory
        run: |
          ls -l

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wechat-devtools-simple-${{ matrix.ARCH }}.build
          path: tmp/build
          if-no-files-found: error
          compression-level: 0
