name: Build DEB Package

on:
  workflow_call:

jobs:
  build-deb:
    name: Build DEB Package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ARCH: ['x86_64']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Generate TAG
        id: tag
        env:
          IS_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          tag='continuous'
          name='Continuous Build'
          if [[ "$IS_TAG" == 'true' ]]; then
            tag="$REF_NAME"
            name="$REF_NAME"
          fi
          echo "tag result: $tag - $name"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "name=$name" >> "$GITHUB_OUTPUT"
      # https://stackoverflow.com/questions/61096521/how-to-use-gpg-key-in-github-actions
      # gpg --generate-key
      # gpg --export-secret-keys YOUR_ID_HERE | base64 > private.key
      - name: Configure GPG Key
        id: gpg
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
          gpg --list-secret-keys jiyecafe@gmail.com
          echo "sign=true" >> "$GITHUB_OUTPUT"
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot devscripts debhelper # debmake lintian pbuilder

      - name: Build Deb Package
        env:
          BUILD_VERSION: ${{ steps.tag.outputs.tag }}
          SIGN_DEB: ${{ steps.gpg.outputs.sign }}
          WINE: 'false'
        run: |
          mkdir -p tmp/build
          tools/build-prepare.sh
          tools/build-deepin.sh "${{ steps.tag.outputs.tag }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wechat-devtools-deb-${{ matrix.ARCH }}.build
          path: tmp/build
          if-no-files-found: error
          compression-level: 0
