name: Build Base Packages

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-src:
    name: Build Base Packages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        ARCH: ['x86_64']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare
        run: echo "$(id -u), $(id -g)"

      - name: Build
        env:
          ACTION_MODE: 'true'
          WINE: 'false'
        run: |
          tools/build-with-docker.sh

      - name: Compress Resources
        run: |
          set -ex
          mkdir -p tmp/src
          test -x electron/electron
          test -f resources/app.asar
          test -f resources/app.asar.unpacked/package.json
          rm -f electron/node electron/node.exe electron/node-18.exe
          install -m 755 node/bin/node electron/node
          ln -s node electron/node.exe
          ln -s node electron/node-18.exe
          tar -zcf tmp/src/src-linux.tar.gz bin electron resources tools

      - name: Compress nodegit
        run: |
          set -ex
          mkdir -p tmp/build
          test -f resources/app.asar.unpacked/node_modules/nodegit/build/Release/nodegit.node
          tar -zcf tmp/build/nodegit.tar.gz \
            -C resources/app.asar.unpacked/node_modules nodegit

      - name: Upload src artifact
        uses: actions/upload-artifact@v4
        with:
          name: wechat-devtools-${{ matrix.ARCH }}.src
          path: tmp/src
          if-no-files-found: error
          compression-level: 0

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: wechat-devtools-${{ matrix.ARCH }}.build
          path: tmp/build
          if-no-files-found: error
          compression-level: 0
