name: Build Packages Linux

on:
  release:
    types: [published]
  push:
    tags:        
      - v*
    branches: [ master, dev, ci, electron]
    paths-ignore:
      - 'README.MD'
      - 'CHANGELOG.MD'
      - 'docs/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-src:
    uses: ./.github/workflows/build-src.yml
    secrets: inherit
  build-tar:
    needs:
      - build-src
    uses: ./.github/workflows/build-tar.yml
    secrets: inherit
  build-deb:
    needs:
      - build-src
    uses: ./.github/workflows/build-deb.yml
    secrets: inherit
  build-flatpak:
    needs:
      - build-src
    uses: ./.github/workflows/build-flatpak.yml
    secrets: inherit
  upload:
    name: Create release and upload artifacts
    needs:
      - build-tar
      - build-deb
      - build-flatpak
      # - build-snap
      # - build-arch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Inspect directory after downloading artifacts
        run: ls -alFR

      - name: Generate TAG
        id: tag
        env:
          IS_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          tag='continuous'
          name='Continuous Build'
          if [[ "$IS_TAG" == 'true' ]]; then
            tag="$REF_NAME"
            name="$REF_NAME"
          fi
          echo "tag result: $tag - $name"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "name=$name" >> "$GITHUB_OUTPUT"

      - name: Create release and upload artifacts
        if: startsWith(github.ref, 'refs/heads/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPIMAGE_EXTRACT_AND_RUN: '1'
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage **build/WeChat*.AppImage **build/*.tar.gz **build/*.deb **build/*.flatpak **build/*.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          name: ${{ steps.tag.outputs.name }}
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            **build/WeChat*.AppImage
            **build/*.tar.gz
            **build/*.deb
            **build/*.flatpak
            **build/*.sh
